### ISSUE TITLE
Typescript errors in build 

### ISSUE THREAD

**Issue by rensftw** [Rebilly/framepay-react#46]
The `yarn build` script seems to generate all expected artifacts, there are many Typescript errors that appear in the logs:
![image](https://user-images.githubusercontent.com/22574186/128745025-4bc47922-06b1-454c-b7dd-5426750c885e.png)

Also the result is misleading because despite the errors teh `build` directory is populated with artifacts (as expected)

**Comment by dariashka** [comment]
No errors found :) 

![](https://i.imgur.com/mWCv555.png)
